---

- name: Entertainment
  hosts: all
  become: yes
  become_user: "{{ user }}"
  vars_files:
    - env_vars/public.yml
  roles:
    - { role: spotify, tags: "spotify"}
    - { role: steam, tags: "steam"}
