---

- name: Schenker Laptop
  hosts: all
  become: yes
  become_user: "{{ user }}"
  vars_files:
    - env_vars/public.yml
  roles:
    - { role: laptop, tags: "laptop"}
    - { role: bumblebee, tags: "bumblebee"}
