---

- name: My Computer
  hosts: all
  become: yes
  remote_user: vagrant
  vars_files:
    - env_vars/public.yml
  roles:
    - { role: desktop, tags: "desktop" }
    - { role: develop, tags: "develop" }
    - { role: dotfiles, tags: "dotfiles" }

