---

- name: My Computer
  hosts: all
  become: yes
  remote_user: vagrant
  vars_files:
    - env_vars/public.yml
  roles:
    - { role: base, tags: "base" }
    - { role: f500.locale, tags: "locale" }
    - { role: desktop, tags: "desktop" }
    - { role: develop, tags: "develop" }
    - { role: dotfiles, tags: "dotfiles" }
    - { role: zsh, tags: "zsh" }
    - { role: emacs, tags: "emacs"}
    - { role: pyenv, tags: "pyenv", become: no}
    - { role: spotify, tags: "spotify"}
    - { role: pip2pi, tags: "pip2pi"}
    - { role: pyside, tags: "pyside"}
    - { role: laptop, tags: "laptop"}
    - { role: bumblebee, tags: "bumblebee"}
    - { role: steam, tags: "steam"}