---

- meta: flush_handlers

- name: Install desktop
  apt: name={{ desktop_package }} force=yes state=latest

- name: Install additional desktop packages
  apt: name={{ item }} force=yes state=latest
  with_items: "{{ desktop_additional_packages }}"

- name: No show HUD hotkey
  gsetting: user={{ ansible_ssh_user }}
            key=org.compiz.integrated.show-hud
            value="['']"

- name: Set launcher favorites
  gsetting: user={{ ansible_ssh_user }}
            key=com.canonical.Unity.Launcher.favorites
            value="['application://org.gnome.Nautius.desktop', 'application://firefox.desktop', 'application://unity-control-center.desktop', 'application://emacs.desktop', 'appliaction://pidgin.desktop', 'unity://running-apps', 'unity://expo-icon', 'unity://devices']"

- name: Map caps to ctrl
  gsetting: user={{ ansible_ssh_user }}
            key=org.gnome.desktop.input-sources.xkb-options
            value="['ctrl:nocaps']"
