---

- meta: flush_handlers

- name: Install desktop
  apt: name={{ desktop_package }} force=yes state=latest

- name: Install additional desktop packages
  apt: name={{ item }} force=yes state=latest
  with_items: "{{ desktop_additional_packages }}"

- name: No show HUD hotkey
  gsetting: user={{ ansible_ssh_user }}
            key=org.compiz.integrated.show-hud
            value="['']"
