---

- name: Update apt
  apt: update_cache={{ update_apt_cache }}

- name: Install desktop
  apt: name={{ desktop_package }} force=yes state=latest

- name: Install additional desktop packages
  apt: name={{ item }} force=yes state=latest
  with_items: "{{ desktop_additional_packages }}"
