---

- name: Update apt
  apt: update_cache={{ update_apt_cache }}

- name: Install ruby
  apt: name=ruby force=yes state=latest

- name: Install homesick
  gem: name=homesick state=latest user_install=no

- name: Clone castles
  command: /usr/local/bin/homesick clone {{ item }}
  become: no
  with_items: "{{ dotfiles_castle_uris }}"

- name: Symlink castles
  command: /usr/local/bin/homesick symlink {{ item }}
  become: no
  with_items: "{{ dotfiles_castle_names }}"
