---

- name: Install build dependencies
  package: name={{ item }} state=present
  with_items:
    - build-essential
    - git
    - cmake
    - libqt4-dev
    - libphonon-dev
    - python2.7-dev
    - python3.4-dev
    - libxml2-dev
    - libxslt1-dev
    - qtmobility-dev
    - libqtwebkit-dev
    - phonon-backend-vlc
