---

- name: Install zsh
  apt: name=zsh force=yes state=latest

- name: Set zsh as default shelsudo chsh -s $(which zsh) vagrantl
  user: name={{ ansible_ssh_user }} shell=/usr/bin/zsh

- name: Download antigen
  get_url:
    url: https://raw.githubusercontent.com/zsh-users/antigen/master/antigen.zsh
    dest: ~/antigen.zsh
  become: no
