---

- name: Add key for Spotify repository
  apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=BBEBDCB318AD50EC6865090613B00F1FD2C19886

- name: Add the Spotify repository
  apt_repository: repo='deb http://repository.spotify.com stable non-free' state=present

- name: Install Spotify
  apt: name=spotify-client state=latest