---

- name: Assures /tmp/emacs-{{ emacs_version }}-src dir exists
  file: path=/tmp/emacs-{{ emacs_version }}-src state=directory

- name: Download emacs source
  unarchive:
    src: http://ftpmirror.gnu.org/emacs/emacs-{{ emacs_version }}.tar.gz
    dest: /tmp/emacs-{{ emacs_version }}-src
    copy: no
    creates: /tmp/emacs-{{ emacs_version }}-src/emacs-{{ emacs_version }}

- name: Install build dependencies for emacs
  apt: name={{ emacs_build_dep }} state=build-dep
  register: emacs_builddep
  changed_when: "'0 newly installed' not in emacs_builddep.stdout_lines[-1]"

- name: Configure emacs build
  shell: ./configure
  args:
    chdir: /tmp/emacs-{{ emacs_version }}-src/emacs-{{ emacs_version }}
    creates: /tmp/emacs-{{ emacs_version }}-src/emacs-{{ emacs_version }}/Makefile

- name: Build emacs
  shell: make
  args:
    chdir: /tmp/emacs-{{ emacs_version }}-src/emacs-{{ emacs_version }}
  register: emacs_build
  changed_when: "emacs_build.stdout.count('Nothing to be done for') != 5"  # any better way?

- name: Install checkinstall
  apt: name=checkinstall state=latest

- name: Get architecture
  command: dpkg --print-architecture
  register: architecture
  changed_when: False
  always_run: True

- name: Create package
  command: checkinstall -y --install=no --pkgname={{ emacs_package_name }}
  args:
    chdir: /tmp/emacs-{{ emacs_version }}-src/emacs-{{ emacs_version }}
    creates: /tmp/emacs-{{ emacs_version }}-src/emacs-{{ emacs_version }}/{{ emacs_package_name }}_{{ emacs_version }}-1_{{ architecture.stdout }}.deb

- name: Install built the emacs package
  apt: deb=/tmp/emacs-{{ emacs_version }}-src/emacs-{{ emacs_version }}/{{ emacs_package_name }}_{{ emacs_version }}-1_{{ architecture.stdout }}.deb

- name: Install fonts
  apt: name={{item}} state=latest
  with_items: "{{ emacs_fonts }}"

- name: Install additional packages for emacs
  apt: name={{item}} state=latest
  with_items: "{{ emacs_add_packages }}"

- name: Install python packages for emacs
  pip: name={{item}} state=latest
  with_items: "{{ emacs_python_packages }}"

- name: Install yasnippet
  git: repo=https://github.com/capitaomorte/yasnippet dest=~/.emacs.d/yasnippet
  become: no

- name: Install elpy
  git: repo=https://github.com/jorgenschaefer/elpy dest=~/.emacs.d/elpy
  become: no

- name: Install helm
  git: repo=https://github.com/emacs-helm/helm dest=~/.emacs.d/helm
  become: no

- name: Build helm
  shell: make
  args:
    chdir: ~/.emacs.d/helm
  become: no

- name: Install helm-swoop
  git: repo=https://github.com/ShingoFukuyama/helm-swoop dest=~/.emacs.d/helm-swoop
  become: no

- name: Download pdf-tools
  git: repo=https://github.com/politza/pdf-tools dest=~/.emacs.d/pdf-tools
  become: no

- name: Install pdf-tools server-deps
  shell: make install-server-deps
  args:
    chdir: ~/.emacs.d/pdf-tools
  become: no

- name: Compile pdf-tools
  shell: make
  args:
    chdir: ~/.emacs.d/pdf-tools
  become: no

- name: Install pdf-tools
  shell: make install-package
  args:
    chdir: ~/.emacs.d/pdf-tools
  become: no

- name: Download Powerline fonts
  git: repo=https://github.com/powerline/fonts dest=~/.emacs.d/powerline-fonts
  become: no

- name: Install powerline fonts
  shell: ./install.sh
  args:
    chdir: ~/.emacs.d/powerline-fonts
  become: no
