---

- name: Assures /tmp/emacs-{{ emacs_version }}-src dir exists
  file: path=/home/{{ansible_ssh_user}}/tp/emacs-{{ emacs_version }}-src state=directory

- name: Download emacs source
  unarchive:
    src: http://ftpmirror.gnu.org/emacs/emacs-{{ emacs_version }}.tar.gz
    dest: /home/{{ansible_ssh_user}}/tp/emacs-{{ emacs_version }}-src
    copy: no
    creates: /home/{{ansible_ssh_user}}/tp/emacs-{{ emacs_version }}-src/emacs-{{ emacs_version }}

- include: debian.yml
  when: ansible_os_family == 'Debian'

- include: redhat.yml
  when: ansible_os_family == 'RedHat'

- name: Install additional packages for emacs
  package: name={{item}} state=latest
  with_items: "{{ emacs_add_packages }}"

- name: Install python packages for emacs
  pip: name={{item}} state=latest
  with_items: "{{ emacs_python_packages }}"

- name: Download Powerline fonts
  git: repo=https://github.com/powerline/fonts dest=~/.emacs.d/powerline-fonts
  become: no

- name: Install powerline fonts
  shell: ./install.sh
  args:
    chdir: ~/.emacs.d/powerline-fonts
  become: no

- name: Install gpg
  package: name=gnupg state=latest

- name: Download mailcrypt
  unarchive:
    src: http://downloads.sourceforge.net/project/mailcrypt/mailcrypt/3.5.9/mailcrypt-3.5.9.tar.gz
    dest: /home/{{ansible_ssh_user}}/tp
    copy: no
    creates: /home/{{ansible_ssh_user}}/tp/mailcrypt-3.5.9

- name: Install mailcrypt
  shell: autoconf && ./configure && make && make install
  args:
    chdir: /home/{{ansible_ssh_user}}/tp/mailcrypt-3.5.9

- name: Download Spotify.el
  git: repo=https://github.com/storax/spotify.el dest=~/.emacs.d/spotify.el
  become: no
