---

- name: Get architecture
  command: arch
  register: architecture
  changed_when: False
  always_run: True

- name: Install emacs build deps
  yum: name={{item}}
  with_items:
    - gcc
    - make
    - ncurses-devel
    - giflib-devel
    - libjpeg-devel
    - libtiff-devel
    - libXpm
    - libXpm-devel
    - libX11-devel
    - gtk2-devel
    - librsvg2-devel
    - rpm-build
    - rpmdevtools
    - libXaw
    - liblockfile
    - libotf
    - emacs-common
    - emacs
    - texinfo
    - poppler-devel
    - poppler-glib
    - poppler
    - evince
    - kdegraphics

- name: Add psychotic ninja repo
  yumrepo:
    name: psychoticninja
    baseurl: http://packages.psychotic.ninja/7/testing/x86_64/RPMS/

- name: Install emacs additional packages
  yum: name={{item}}
  with_items:
    - libpng-devel
    - zlib-devel
    - poppler-devel
    - dejavu-fonts-common
    - levien-inconsolata-fonts
    - ack
    - ImageMagick
    - sqlite
    - dictd

- name: Create RPM Sourcetrees
  command: rpmdev-setuptree

- name: Install checkinstall
  yum: name=ftp://ftp.pbone.net/mirror/ftp5.gwdg.de/pub/opensuse/repositories/home:/andnagy/RedHat_RHEL-6/x86_64/checkinstall-1.6.2-20.2.x86_64.rpm

- name: Configure emacs build
  shell: ./configure --without-toolkit-scroll-bars --with-x-toolkit=no
  args:
    chdir: /home/{{ansible_ssh_user}}/tp/emacs-{{ emacs_version }}-src/emacs-{{ emacs_version }}
    creates: /home/{{ansible_ssh_user}}/tp/emacs-{{ emacs_version }}-src/emacs-{{ emacs_version }}/Makefile

- name: Build emacs
  shell: make
  args:
    chdir: /home/{{ansible_ssh_user}}/tp/emacs-{{ emacs_version }}-src/emacs-{{ emacs_version }}
  register: emacs_build
  changed_when: "emacs_build.stdout.count('Nothing to be done for') != 5"  # any better way?

- name: Create package
  command: make install
  args:
    chdir: /home/{{ansible_ssh_user}}/tp/emacs-{{ emacs_version }}-src/emacs-{{ emacs_version }}
    creates: /usr/local/bin/emacs
