---

- name: Add git repo
  apt_repository: repo='ppa:git-core/ppa' state=present

- name: Install development tools
  apt: name={{ item }} force=yes state=latest
  with_items: "{{ develop_tools }}"

- name: Add guake repo
  apt_repository: repo='ppa:webupd8team/unstable' state=present

- name: Add virtualbox repo key
  apt_key: url=https://www.virtualbox.org/download/oracle_vbox.asc state=present

- name: Add virtualbox repo
  apt_repository:
    repo: 'deb http://download.virtualbox.org/virtualbox/debian trusty contrib'
    state: present

- name: Install ruby dev
  apt: name=ruby-dev state=latest

- name: Install python dev
  apt: name={{item}} state=latest
  with_items:
    - python2.7-dev
    - python3.4-dev

- name: Download vagrant package
  get_url:
    url: https://releases.hashicorp.com/vagrant/{{ develop_vagrant_version}}/vagrant_{{ develop_vagrant_version}}_x86_64.deb
    dest: /home/{{ansible_ssh_user}}/tp/vagrant_{{ develop_vagrant_version}}.deb

- name: Install vagrant
  apt: deb=/home/{{ansible_ssh_user}}/tp/vagrant_{{ develop_vagrant_version}}.deb

- name: Install required packages for ansible
  apt:
   name: "{{item}}"
   state: latest
   update_cache: yes
  with_items:
   - git
   - python-setuptools
   - python-dev
   - build-essential
