---

- name: Add git repo
  apt_repository: repo='ppa:git-core/ppa' state=present

- name: Add git repo
  apt_repository: repo='ppa:webupd8team/unstable' state=present

- name: Add virtualbox repo key
  apt_key: url=https://www.virtualbox.org/download/oracle_vbox.asc state=present

- name: Add virtualbox repo
  apt_repository:
    repo: 'deb http://download.virtualbox.org/virtualbox/debian trusty contrib'
    state: present

- name: Install development tools
  apt: name={{ item }} force=yes state=latest
  with_items: "{{ develop_tools }}"

- name: Install travis
  gem: name=travis state=latest user_install=no

- name: Install python tools
  pip: name={{item}} state=latest
  with_items: "{{ develop_python_tools }}"

- name: Download vagrant package
  get_url:
    url: https://releases.hashicorp.com/vagrant/{{ develop_vagrant_version}}/vagrant_{{ develop_vagrant_version}}_x86_64.deb
    dest: /tmp/vagrant_{{ develop_vagrant_version}}.deb

- name: Install vagrant
  apt: deb=/tmp/vagrant_{{ develop_vagrant_version}}.deb

- name: Create packer dir
  file: path="{{ develop_packer_dir}}" state=directory
  become: no

- name: Check if packer installed
  stat: path="{{ develop_packer_dir}}/packer"
  register: packer
  become: no

- name: Check packer version
  command: "{{ develop_packer_dir}}/packer --version"
  become: no
  register: packerversion
  when: packer.stat.exists
  failed_when: False
  changed_when: "packerversion.stdout != '{{ develop_packer_version}}'"

- name: Install packer
  unarchive:
    src: https://releases.hashicorp.com/packer/{{ develop_packer_version}}/packer_{{ develop_packer_version}}_linux_amd64.zip
    dest: "{{ develop_packer_dir }}"
    copy: no
  become: no
  when: "not packer.stat.exists or packerversion.changed"

- name: Install required packages for ansible
  apt:
   name: "{{item}}"
   state: latest
   update_cache: yes
  with_items:
   - git
   - python-setuptools
   - python-dev
   - build-essential

- name: Install required python packages for ansible
  pip:
   name: "{{item}}"
   state: latest
  with_items:
   - paramiko
   - PyYAML
   - Jinja2
   - httplib2
   - six

- name: Clone ansible
  git:
   repo: https://github.com/ansible/ansible.git
   recursive: yes
   dest: "{{develop_ansible_dir}}"
   accept_hostkey: yes
   update: no
  become: no

- name: Clone repositories
  git:
    repo: "{{item[0]}}"
    dest: "{{item[1]}}"
    update: no
  become: no
  with_together:
    - "{{ develop_repo_urls }}"
    - "{{ develop_repo_dests }}"
