---

- include: debian.yml
  when: ansible_os_family == 'Debian'

- include: redhat.yml
  when: ansible_os_family == 'RedHat'

- name: Install travis
  gem: name=travis state=latest user_install=no

- name: Install python tools
  pip: name={{item}} state=latest
  with_items: "{{ develop_python_tools }}"

- name: Create packer dir
  file: path="{{ develop_packer_dir}}" state=directory
  become: no

- name: Check if packer installed
  stat: path="{{ develop_packer_dir}}/packer"
  register: packer
  become: no

- name: Check packer version
  command: "{{ develop_packer_dir}}/packer --version"
  become: no
  register: packerversion
  when: packer.stat.exists
  failed_when: False
  changed_when: "packerversion.stdout != '{{ develop_packer_version}}'"

- name: Install packer
  unarchive:
    src: https://releases.hashicorp.com/packer/{{ develop_packer_version}}/packer_{{ develop_packer_version}}_linux_amd64.zip
    dest: "{{ develop_packer_dir }}"
    copy: no
  become: no
  when: "not packer.stat.exists or packerversion.changed"

- name: Install required python packages for ansible
  pip:
   name: "{{item}}"
   state: latest
  with_items:
   - paramiko
   - PyYAML
   - Jinja2
   - httplib2
   - six

- name: Clone ansible
  git:
   repo: https://github.com/ansible/ansible.git
   recursive: yes
   dest: "{{develop_ansible_dir}}"
   accept_hostkey: yes
   update: no
  become: no

- name: Clone repositories
  git:
    repo: "{{item[0]}}"
    dest: "{{item[1]}}"
    update: no
  become: no
  with_together:
    - "{{ develop_repo_urls }}"
    - "{{ develop_repo_dests }}"
