---

- name: Add git repo
  apt_repository: repo='ppa:git-core/ppa' state=present

- name: Install development tools
  apt: name={{ item }} force=yes state=latest
  with_items: "{{ develop_tools }}"

- name: Install travis
  gem: name=travis state=latest user_install=no

- name: Install python tools
  pip: name={{item}} state=latest
  with_items: "{{ develop_python_tools }}"