---

- name: Install requirements
  yum: name={{ item }} state=present
  become: yes
  with_items:
    - make
    - build-essential
    - openssl-devel
    - zlib1g-devel
    - libbz2-devel
    - libreadline-devel
    - libsqlite3-devel
    - wget
    - curl
    - llvm

- name: Install
  git: repo=https://github.com/yyuu/pyenv.git dest={{ pyenv_root }}

- name: Install virtualenv
  git: repo=https://github.com/yyuu/{{ item }}.git dest={{ pyenv_root }}/plugins/{{ item }}
  with_items:
    - pyenv-virtualenv
    - pyenv-virtualenvwrapper
  when: pyenv_virtualenv
