---

- stat: path=~/.pyenv
  register: pyenv_dirstat
  become: no

- name: Download pyenv installer
  get_url:
    url: https://raw.githubusercontent.com/yyuu/pyenv-installer/master/bin/pyenv-installer
    dest: /tmp/pyenv-installer
    mode: 0777
  become: no
  when: pyenv_dirstat.stat.exists != True
  register: pyenvdownload

- name: Install pyenv
  command: /tmp/pyenv-installer
  become: no
  args:
    creates: ~/.pyenv
  when: pyenvdownload.changed

- name: Install pyenv-virtualenvwrapper
  git:
    repo: https://github.com/yyuu/pyenv-virtualenvwrapper.git
    dest: ~/.pyenv/plugins/pyenv-virtualenvwrapper
  become: no
