---

- name: Install pyenv
  shell: curl -L https://raw.githubusercontent.com/yyuu/pyenv-installer/master/bin/pyenv-installer | bash
  become: no
  args:
    creates: "{{ lookup('env','HOME') }}/.pyenv"

- name: Install pyenv-virtualenvwrapper
  git: repo=https://github.com/yyuu/pyenv-virtualenvwrapper.git dest="{{ lookup('env','HOME') }}/.pyenv/plugins/pyenv-virtualenvwrapper"
  become: no
