---
- include: pyenv.yml

- name: Install versions
  command: creates={{ pyenv_root }}/versions/{{ item }} {{ pyenv_root }}/bin/pyenv install {{ item }}
  with_items: pyenv_versions
  environment: "{{ pyenv_install_environ }}"

- include: versions.yml
  versions: "{{ pyenv_default_versions }}"
  dest: "{{ pyenv_root }}/version"

- include: versions.yml
  versions: "{{ pyenv_project_versions }}"
  dest: "{{ pyenv_project_root }}/.python-version"

- name: Add to run commands
  lineinfile: >
    dest={{ pyenv_runcom }}
    state=present
    create=yes
    line="{{ item }}"
  with_items:
    - if which pyenv > /dev/null; then
    - "    export PYENV_ROOT=\\\"$HOME/.pyenv\\\""
    - "    export PATH=\\\"$PYENV_ROOT/bin:$PATH\\\""
    - "    eval \\\"$(pyenv init -)\\\""
    - "fi # pyenv"
  when: pyenv_runcom

- name: Install virtualenvwrapper
  pip: name=virtualenvwrapper state=latest
  become: yes
  when: pyenv_virtualenv

- name: Add virtualenv to run commands
  lineinfile: >
    dest={{ pyenv_runcom }}
    state=present
    create=yes
    insertbefore="fi # pyenv"
    line="    pyenv virtualenvwrapper_lazy"
  when: pyenv_virtualenv and pyenv_runcom

- name: Configure virtualenvwrapper
  lineinfile: >
    dest={{ pyenv_runcom }}
    state=present
    create=yes
    line="{{ item }}"
  with_items:
    - export WORKON_HOME=\"$HOME/.virtualenvs\"
    - export PROJECT_HOME=\"$HOME/development\"
  when: pyenv_virtualenv and pyenv_runcom

- name: Install python packages for each version
  pip: name="{{item[0]}}" state=latest executable={{ pyenv_root }}/versions/{{ item[1] }}/bin/pip
  with_nested:
    - "{{ pyenv_python_packages}}"
    - "{{ pyenv_versions }}"