---

- name: Upgrade
  yum: name=* state=latest update_cache=yes

- name: Ensure bash, OpenSSl are the latest versions
  yum: name={{ item }} state=latest
  with_items:
    - bash
    - openssl-devel
    - openssl

- name: Install base packages
  yum: name={{ item }} state=present
  with_items:
    - kernel-devel
    - gcc-c++
    - "@Development tools"

- name: Make sure ntp is running
  service: name=ntpd state=started enabled=yes
